# Generated by Django 4.2.1 on 2023-06-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0002_agent_department_agent_position_agent_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
