# Generated by Django 4.2.1 on 2023-06-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0003_agent_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="profiles/default.jpg",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
